import {localLeftIds} from '../../src/workflows/local-exclusions';
import { MissingScores } from '../components/missing-scores';
import { allMissingScores } from '../../src/workflows/missing-sections';
import { DashboardInsights } from '../components/dashboard-insights';
import { dashboardInsights, earlierEvent } from '../../src/workflows/dashboard';
import { PageHeader } from '../components/ui';
import Link from 'next/link';
import { requireStaff } from '../../src/auth/session';
import { eventContext, registrations, priorRegistrations } from '../../src/workflows/data';
import { StaffShell } from '../components/staff-shell';
import { EventPicker, Historical } from '../components/workflow';
export default async function Admin(){const {client,profile}=await requireStaff(true);const {events,event}=await eventContext(client);const rows=event?await registrations(client,event.id):[];const earlier=event?events.filter(e=>earlierEvent(e,event)):[];const insights=dashboardInsights(rows,await priorRegistrations(client,earlier.map(e=>e.id)),earlier.length>0,await localLeftIds());
 const previous=event?events.find(e=>e.event_year===event.event_year-1&&e.legacy_source_key==='qkby:2025'):undefined;const previousRows=previous?await registrations(client,previous.id):[];const attendance={year:event?.event_year??0,previousYear:previous?.event_year??null,previousCount:previous?previousRows.filter(r=>['Checked-in','Judged'].includes(r.status??'')).length:null};
 const left=await localLeftIds();const gaps=allMissingScores(rows.filter(r=>!left.includes(r.id)));
 return <StaffShell role={profile.app_role} name={profile.display_name}><PageHeader title={`Event dashboard`} actions={event?<a className="button secondary" href={`/admin/export-season?event=${event.id}`}>Export Event</a>:undefined}/><EventPicker events={events} event={event}/>{event?<><h2>{event.name}</h2><Historical event={event}/><p>{event.judging_open?'Open for judging':'Judging closed'} · {event.event_date??'Event date not recorded'}</p><section className="card section-space"><h2>Keep the event moving</h2><p>Review cars waiting for check-in, outstanding payments, or unfinished judging.</p><div className="actions"><Link className="button" href="/admin/registrations?status=Registered">Check in arrivals</Link><Link className="button secondary" href="/admin/registrations?paid=Unpaid&status=attending">Review unpaid</Link><Link className="button secondary" href="/admin/scores">Judging progress</Link></div></section><DashboardInsights data={insights} attendance={attendance} missingSectionsWidget={<MissingScores rows={gaps} eventName={event.name}/>}/><div className="grid">{[['Participants','Find an entrant, view their cars or add a participant.','/admin/participants'],['Registrations / Cars','Register existing vehicles, check in and update payments.','/admin/registrations'],['Scores','Review judging progress, section history and Quick Edit.','/admin/scores'],['Awards','Live winner summary and historical results.','/admin/awards']].map(([title,description,url])=><Link key={url} className="card nav-card" href={url}><h2>{title}</h2><p>{description}</p></Link>)}</div></>:<p>Create your first event from <Link href="/admin/events">Events</Link>.</p>}</StaffShell>;
}
