import { DashboardInsights } from '../components/dashboard-insights';
import { dashboardInsights, earlierEvent } from '../../src/workflows/dashboard';
import { PageHeader, StatCard } from '../components/ui';
import Link from 'next/link';
import { requireStaff } from '../../src/auth/session';
import { eventContext, registrations, priorRegistrations } from '../../src/workflows/data';
import { statistics } from '../../src/workflows/types';
import { StaffShell } from '../components/staff-shell';
import { EventPicker, Historical } from '../components/workflow';
export default async function Admin(){const {client,profile}=await requireStaff(true);const {events,event}=await eventContext(client);const rows=event?await registrations(client,event.id):[];const stats=statistics(rows);const earlier=event?events.filter(e=>earlierEvent(e,event)):[];const insights=dashboardInsights(rows,await priorRegistrations(client,earlier.map(e=>e.id)),earlier.length>0);
 return <StaffShell role={profile.app_role} name={profile.display_name}><PageHeader title={`Event dashboard`}/><EventPicker events={events} event={event}/>{event?<><h2>{event.name}</h2><Historical event={event}/><p>{event.judging_open?'Open for judging':'Judging closed'} · {event.event_date??'Event date not recorded'}</p><section className="card section-space"><h2>Keep the event moving</h2><p>Review cars waiting for check-in, outstanding payments, or unfinished judging.</p><div className="actions"><Link className="button" href="/admin/registrations?status=Registered">Check in arrivals</Link><Link className="button secondary" href="/admin/registrations?paid=Unpaid">Review unpaid</Link><Link className="button secondary" href="/admin/scores">Judging progress</Link></div></section><div className="metrics">{[['Registered',stats.registered],['Checked in',stats.checked],['Judged',stats.judged],['Paid',stats.paid]].map(([name,value])=><StatCard key={name} label={String(name)} value={value}/>)}</div><p className="hint">Checked in: {stats.checkedPercent.toFixed(2)}% of registered · Judged: {stats.judgedPercent.toFixed(2)}% of checked in · Paid: {stats.paidPercent.toFixed(2)}% of registered. Counts preserve the legacy rules, including Paid archived cars.</p><DashboardInsights data={insights}/><div className="grid">{[['Participants','Find an entrant, view their cars or add a participant.','/admin/participants'],['Registrations / Cars','Register existing vehicles, check in and update payments.','/admin/registrations'],['Scores','Review judging progress, section history and Quick Edit.','/admin/scores'],['Awards','Live winner summary and historical results.','/admin/awards']].map(([title,description,url])=><Link key={url} className="card nav-card" href={url}><h2>{title}</h2><p>{description}</p></Link>)}</div></>:<p>Create your first event from <Link href="/admin/events">Events</Link>.</p>}</StaffShell>;
}
