import { CarColorSelect } from '../../../components/car-color-select';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireStaff } from '../../../../src/auth/session';
import { directory,eventContext,registrations } from '../../../../src/workflows/data';
import { StaffShell } from '../../../components/staff-shell';
import { PageHeader,StatusBadge,EmptyState } from '../../../components/ui';
import { EventPicker,Historical } from '../../../components/workflow';
import { ActionForm } from '../../../components/action-form';
import { CarFields } from '../../participants/fields';
import { arriveCar,saveCar } from '../../workflow-actions';
export default async function CheckIn({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const {client,profile}=await requireStaff(true);const [[people,cars],{events,event}]=await Promise.all([directory(client),eventContext(client)]);const person=people.find(p=>p.id===id);if(!person)notFound();const owned=cars.filter(c=>c.participant_id===id);const rows=event?(await registrations(client,event.id)).filter(r=>r.participant_id===id):[];
 return <StaffShell role={profile.app_role} name={profile.display_name}><Link href="/admin/participants"><ArrowLeft className="action-icon" size={18} strokeWidth={1.75} aria-hidden="true"/> Find another participant</Link><PageHeader title={`Check in · ${person.name}`} description="Confirm their details, choose a car, record payment, then print its car sheet."/><EventPicker events={events} event={event}/>{event&&<Historical event={event}/>}<section className="card"><h2>1. Confirm participant</h2><p>{person.name} · {person.email} · {person.phone||'No phone recorded'}</p><p>{[person.address,person.city,person.state,person.zip].filter(Boolean).join(', ')}</p><Link href={`/admin/participants/${id}`}>Edit participant details</Link></section>{event&&!event.legacy_source_key?<><section className="section-space"><h2>2. Choose a car and confirm payment</h2><p>Each car gets its number when you complete check-in. Existing numbers are reused when reprinting.</p><div className="grid">{owned.map(car=>{const reg=rows.find(r=>r.car_id===car.id);return <article className="card" id={`car-${car.id}`} key={car.id}><h3>{car.year} {car.make} {car.model}</h3><div className="badge-row"><StatusBadge value={reg?.status==='Registered'?'Pre-registered':reg?.status??'Walk-in'}/><StatusBadge value={reg?.payment_status??'Unpaid'}/>{reg?.car_number&&<strong>#{reg.car_number}</strong>}</div>{reg?.car_number&&<p>This event registration already has a number. Its score and history stay intact.</p>}<ActionForm action={arriveCar} submit={reg?.car_number?'Confirm payment & open sheet':'Complete check-in & print sheet'}><input type="hidden" name="event" value={event.id}/><input type="hidden" name="participant" value={id}/><input type="hidden" name="car" value={car.id}/><div className="grid"><CarColorSelect value={reg?.vehicle_color??car.color} required/><label>Payment for this car<select name="payment" defaultValue={reg?.payment_status??'Unpaid'}><option>Unpaid</option><option>Paid</option></select></label></div><p className="hint">Collect payment manually if needed, then choose Paid. This does not charge a card.</p></ActionForm></article>;})}</div>{!owned.length&&<EmptyState title="Add their first car below"/>}</section><details className="card section-space"><summary>Add a new car</summary><ActionForm action={saveCar} submit="Save car"><CarFields participant={id}/></ActionForm></details></>:<EmptyState title="Select a new event to check in arrivals" description="Historical registrations remain read-only."/>}</StaffShell>;
}
