import Link from 'next/link';
import { requireStaff } from '../../../src/auth/session';
import { directory,eventContext } from '../../../src/workflows/data';
import { StaffShell } from '../../components/staff-shell';
import { PageHeader } from '../../components/ui';
import { ActionForm } from '../../components/action-form';
import { configurePortal,reviewRequest } from './actions';
type Request={id:string;event_id:string;participant_id:string|null;details:{name:string;email?:string;phone?:string;city?:string;state?:string};cars:{year:string;make:string;model:string}[]};
export default async function Requests({searchParams}:{searchParams:Promise<{request?:string;participant?:string}>}){
 const {client,profile}=await requireStaff(true);const params=await searchParams;
 const [{events},[people,cars],result]=await Promise.all([eventContext(client),directory(client),client.rpc('admin_registration_requests')]);
 const requests:Request[]=result.data?.requests??[];
 return <StaffShell role={profile.app_role} name={profile.display_name}><PageHeader title="Registration requests"/><p>Review earlier pending requests. New public submissions now create pre-registrations immediately.</p>{result.error?<p role="status">Public registration requires the pending database migration. No registration requests can be submitted yet.</p>:<><details className="card"><summary>Public registration settings</summary><ActionForm action={configurePortal} submit="Save registration setting"><label>Accept public registrations for<select name="event" defaultValue={result.data?.event??''}><option value="">Closed</option>{events.filter(e=>!e.legacy_source_key).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><p>This is independent of judging. Verify the selected event before opening registration.</p></ActionForm></details>{requests.map(r=>{const selected=r.participant_id??(params.request===r.id?params.participant:null);const person=people.find(p=>p.id===selected);return <section className="card stack" key={r.id}><h2>{person?.name??r.details.name}</h2><p>{events.find(e=>e.id===r.event_id)?.name} · {r.details.city} {r.details.state}</p><p>{r.details.email} {r.details.phone}</p>{!r.participant_id&&<form className="filters"><input type="hidden" name="request" value={r.id}/><label>Match a participant<select name="participant" defaultValue={selected??''}><option value="">Create a new participant after review</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.city} · {p.phone}</option>)}</select></label><button className="secondary">Show cars</button></form>}<div className="request-review-actions"><ActionForm action={reviewRequest} className="stack accept-request" submit="Accept pre-registration"><input type="hidden" name="request" value={r.id}/><input type="hidden" name="participant" value={selected??''}/>{r.cars.map((car,i)=><label key={i}>{car.year} {car.make} {car.model}<select name="car"><option value="">Add this as a new car</option>{cars.filter(c=>c.participant_id===selected).map(c=><option key={c.id} value={c.id}>{c.year} {c.make} {c.model}</option>)}</select></label>)}<p>{person?`Use ${person.name} without changing their current contact information.`:'Create a new participant using these submitted details. Check for an existing record first.'} Car numbers and payment are handled at check-in.</p></ActionForm><ActionForm action={reviewRequest} className="stack dismiss-request" submit="Dismiss request"><input type="hidden" name="request" value={r.id}/><input type="hidden" name="dismiss" value="yes"/></ActionForm></div>{person&&<Link href={`/admin/check-in/${person.id}`}>Open participant check-in</Link>}</section>})}{!requests.length&&<p className="empty">No pending registration requests.</p>}</>}</StaffShell>;
}
