import type { dashboardInsights } from '../../src/workflows/dashboard';
type Insights=ReturnType<typeof dashboardInsights>;
function Pie({title,count,total,detail,color="var(--lions-green)"}:{title:string;count:number;total:number;detail:string;color?:string}){
 const percent=total?count/total*100:0;
 return <section className="card dashboard-chart"><h2>{title}</h2><div className="dashboard-chart-body"><div className="dashboard-donut" role="img" aria-label={total?`${count} of ${total}, ${percent.toFixed(1)}%`:'No cars yet'} style={{background:`conic-gradient(${color} ${percent}%, var(--chart-track) 0)`}}><span>{total?`${Math.round(percent)}%`:'—'}</span></div><div><strong>{count} <small>of {total} cars</small></strong><p>{detail}</p></div></div></section>;
}
function Ranking({title,heading,rows}:{title:string;heading:string;rows:Insights['makes']}){return <section className="card"><h2>{title}</h2><p className="hint">Share of registered cars in this event</p><div className="dashboard-ranking"><table><thead><tr><th>{heading}</th><th>Cars</th><th>% of total</th></tr></thead><tbody>{rows.map(row=><tr key={row.label}><td>{row.label}</td><td>{row.count}</td><td>{row.percent.toFixed(1)}%</td></tr>)}</tbody></table>{!rows.length&&<p>No registered cars yet.</p>}</div></section>;}
export function DashboardInsights({data}:{data:Insights}){return <>
 <div className="dashboard-charts"><Pie title="Checked-In" count={data.checked} total={data.total} detail="Arrived, including judged cars"/><Pie title="Paid" count={data.paid} total={data.total} detail="Payment marked Paid"/><Pie color="var(--lions-green)" title="Judged" count={data.judged} total={data.checked} detail="Judging completed"/></div>
 <section className="card section-space"><h2>New & returning cars</h2>{data.newCars===null?<p>No earlier event baseline is available to identify new or returning cars.</p>:<><div className="dashboard-car-mix"><div><strong>{data.newCars}</strong><span>New cars</span></div><div><strong>{data.returning}</strong><span>Returning cars</span></div><div><strong>{data.total?`${(data.newCars/data.total*100).toFixed(1)}%`:'—'}</strong><span>New cars / registered cars</span></div></div><p className="hint">Returning means this car appears in an earlier event record, including the 2025 legacy snapshot. This does not establish prior attendance. New means no earlier event record exists.</p></>}</section>
 <div className="dashboard-tables"><Ranking title="Top 5 locations" heading="City, State" rows={data.locations}/><Ranking title="Top 5 car makes" heading="Make" rows={data.makes}/></div><p className="hint dashboard-disclaimer">Charts and tables exclude archived and unclassified registrations. Locations use current participant details; makes use event vehicle snapshots. Each car counts once, including multiple cars from one participant.</p>
 </>;}
