import Link from 'next/link';
import type { dashboardInsights } from '../../src/workflows/dashboard';
type Insights=ReturnType<typeof dashboardInsights>;
function Pie({title,count,total,detail,href,action}:{title:string;count:number;total:number;detail:string;href:string;action:string}){
 const percent=total?count/total*100:0;
 const angle=Math.min(100,Math.max(0,percent))/100*Math.PI*2;
 const progress=Math.min(1,Math.max(0,percent/100));
 const start=progress<=.5?[255,91,53]:[235,183,0],end=progress<=.5?[235,183,0]:[0,171,104];
 const fraction=progress<=.5?progress*2:(progress-.5)*2;
 const tipColor=`rgb(${start.map((v,i)=>Math.round(v+(end[i]-v)*fraction)).join(',')})`;
 return <section className="card dashboard-chart"><h2>{title}</h2><div className="dashboard-chart-body"><div className="dashboard-donut" role="img" aria-label={total?`${count} of ${total}, ${percent.toFixed(1)}%`:'No cars yet'} style={{background:`conic-gradient(transparent 0% ${percent}%, var(--chart-track) ${percent}% 100%), conic-gradient(#ff5b35 0%, #ebb700 50%, #00ab68 100%)`}}>{percent>0&&percent<100&&<><i className="donut-cap" style={{left:64,top:4.5,background:'#ff5b35'}}/><i className="donut-cap" style={{left:64+59.5*Math.sin(angle),top:64-59.5*Math.cos(angle),background:tipColor}}/></>}<span>{total?`${Math.round(percent)}%`:'—'}</span></div><div><strong>{count} <small>of {total} cars</small></strong><p>{detail}</p></div></div><Link className="button secondary chart-action" href={href}>{action}</Link></section>;
}
function Ranking({title,heading,rows}:{title:string;heading:string;rows:Insights['makes']}){return <section className="card"><h2>{title}</h2><p className="hint">Share of registered cars in this event</p><div className="dashboard-ranking"><table><thead><tr><th>{heading}</th><th>Cars</th><th>% of total</th></tr></thead><tbody>{rows.map(row=><tr key={row.label}><td>{row.label}</td><td>{row.count}</td><td>{row.percent.toFixed(1)}%</td></tr>)}</tbody></table>{!rows.length&&<p>No registered cars yet.</p>}</div></section>;}
export function DashboardInsights({data,attendance}:{data:Insights;attendance:{year:number;previousYear:number|null;previousCount:number|null}}){return <>
 <div className="dashboard-charts"><Pie href="/admin/registrations?status=Registered" action="View Registrations" title="Checked-In" count={data.checked} total={data.total} detail="Arrived, including judged cars"/><Pie href="/admin/registrations?paid=Unpaid&status=attending" action="View Unpaid" title="Paid" count={data.paid} total={data.checked} detail="Attending cars marked Paid"/><Pie href="/admin/registrations?status=Checked-in" action="View Un-judged" title="Judged" count={data.judged} total={data.checked} detail="Judging completed"/></div>
 <Attendance current={data.checked} {...attendance}/>
 <section className="card section-space"><h2>New & returning cars</h2>{data.newCars===null?<p>No earlier event baseline is available to identify new or returning cars.</p>:<><div className="dashboard-car-mix"><div><strong>{data.newCars}</strong><span>New cars</span></div><div><strong>{data.returning}</strong><span>Returning cars</span></div><div><strong>{data.total?`${(data.newCars/data.total*100).toFixed(1)}%`:'—'}</strong><span>New cars / registered cars</span></div></div><p className="hint">Returning means this car appears in an earlier event record, including the 2025 legacy snapshot. This does not establish prior attendance. New means no earlier event record exists.</p></>}</section>
 <div className="dashboard-tables"><Ranking title="Top 5 locations" heading="City, State" rows={data.locations}/><Ranking title="Top 5 car makes" heading="Make" rows={data.makes}/></div><p className="hint dashboard-disclaimer">Charts and tables exclude archived and unclassified registrations. Locations use current participant details; makes use event vehicle snapshots. Each car counts once, including multiple cars from one participant.</p>
 </>;}

function Attendance({current,year,previousYear,previousCount}:{current:number;year:number;previousYear:number|null;previousCount:number|null}) {
 const change=previousCount?((current-previousCount)/previousCount*100):null;
 const capacity=Math.max((previousCount??0)*1.5,current,1);
 const fill=current/capacity*100;
 const benchmark=(previousCount??0)/capacity*100;
 return <section className="card section-space attendance-summary"><h2>Attendance compared with last year</h2><div className="dashboard-car-mix"><div><strong>{current}</strong><span>{year} attending</span></div><div><strong>{previousCount??'—'}</strong><span>{previousYear?`${previousYear} attended`:'No previous-year baseline'}</span></div><div><strong>{change===null?'—':`${change>0?'+':''}${change.toFixed(1)}%`}</strong><span>{change===null?'Change unavailable':change>0?'Increase':change<0?'Below last year':'No change'}</span></div></div>{previousCount!==null&&previousCount>0&&<div className="attendance-meter" role="img" aria-label={`${current} attendees so far; last year’s benchmark is ${previousCount}.`}><div className="attendance-meter-track"><div className="attendance-meter-fill" style={{width:`${fill}%`,background:`linear-gradient(to right, #ff5b35 0%, #ebb700 ${current?previousCount/current*50:50}%, #00ab68 ${current?previousCount/current*100:100}%)`}}/></div><span className="attendance-meter-tick" style={{left:`${benchmark}%`}}/><span className="attendance-meter-label" style={{left:`${benchmark}%`}}>Last year: {previousCount}</span></div>}<p className="hint">Attending means Checked-in or Judged; pre-registered and Archived cars are excluded. The marker shows last year’s recorded attendance. Refresh to update the current count. Only the validated historical event is used as a baseline.</p></section>;
}
