import { EmptyState } from './ui';
import Link from 'next/link';
import type { EventRow, HistoryDisplay } from '../../src/workflows/types';
import { sectionLabels } from '../../src/workflows/types';
import { chooseEvent } from '../admin/workflow-actions';
export function EventPicker({events,event}:{events:EventRow[];event:EventRow|null}){return <div className="event-bar"><form action={chooseEvent}><label>Selected event<select name="event" defaultValue={event?.id}>{events.map(e=><option key={e.id} value={e.id}>{e.name} ({e.event_year}){e.legacy_source_key?' — historical':''}</option>)}</select></label><button className="secondary">Select event</button></form><Link className="button secondary manage-events" href="/admin/events">Manage events</Link></div>;}
export function Historical({event}:{event:EventRow}){return event.legacy_source_key?<p className="notice">Historical 2025 legacy snapshot · read-only. Archived records do not establish attendance. Vehicle details are event snapshots.</p>:null;}
export function Empty({children}:{children:React.ReactNode}){return <EmptyState title="Nothing here yet" description={typeof children==='string'?children:undefined}/>;}
export function Progress({value}:{value:number}){return <span className="progress-label"><progress max={100} value={value}/>{Math.round(value)}%</span>;}
export function HistoryTable({history}:{history:HistoryDisplay[]}){return <div className="table-wrap"><table><thead><tr><th>Action / section</th><th>Judge</th><th>When</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td data-label="Action / section">{h.action_type==='admin_quick_edit'?'Administrative Quick Edit':sectionLabels[h.section as keyof typeof sectionLabels]??h.section}</td><td data-label="Judge">{h.judge_name_snapshot??'Historical judge'}</td><td data-label="When">{h.submitted_at?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Indiana/Indianapolis'}).format(new Date(h.submitted_at))+' Eastern':<>{h.legacy_timestamp_raw??'Unknown'}<small>Legacy wall time; timezone unresolved{h.legacy_updated_at_raw?` · alternate clock: ${h.legacy_updated_at_raw}`:''}</small></>}</td></tr>)}</tbody></table>{!history.length&&<Empty>No submissions yet.</Empty>}</div>;}
