import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { database } from './helpers';
import { FIELDS, MAXIMA, SECTIONS } from '../src/domain/scoring';
import { provisionAccount } from '../src/auth/accounts';
import type { SupabaseClient } from '@supabase/supabase-js';
import { readFile } from 'node:fs/promises';
test('RLS, atomic submissions, zero/blank, repeat/retry, Quick Edit, attribution and deactivation',async()=>{
  const {db,close}=await database();const admin=randomUUID(),judge=randomUUID(),outsider=randomUUID();
  const as=async(id:string,role='authenticated')=>{await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`SET ROLE ${role}`);};
  try{
    for(const id of [admin,judge,outsider]) await db.query('INSERT INTO auth.users(id,email) VALUES ($1,$2)',[id,`${id}@example.invalid`]);
    await db.query("INSERT INTO public.profiles(id,display_name,app_role,is_active) VALUES ($1,'Admin','admin',true),($2,'Judge','judge',true),($3,'No role',NULL,true)",[admin,judge,outsider]);
    const event=(await db.query("INSERT INTO public.events(slug,name,event_year,judging_open) VALUES ('test','Test',2026,true) RETURNING id")).rows[0].id;
    const participant=(await db.query("INSERT INTO public.participants(name,email) VALUES ('Private','private@example.invalid') RETURNING id")).rows[0].id;
    const car=(await db.query("INSERT INTO public.cars(participant_id,year,make,model) VALUES ($1,1955,'Test','Snapshot') RETURNING id",[participant])).rows[0].id;
    await as(admin);
    const registration=(await db.query('SELECT * FROM public.admin_register_car($1,$2)',[event,car])).rows[0].id;
    await as('', 'anon');
    await assert.rejects(db.query('SELECT * FROM public.participants'),/permission denied/);
    assert.equal((await db.query('SELECT * FROM public.public_events()')).rows.length,0);
    await assert.rejects(db.query('SELECT public.submit_lions_choice($1)',[registration]),/permission denied/);
    await as(outsider);await assert.rejects(db.query('SELECT * FROM public.judge_event()'),/Access denied/);
    await as(judge);
    assert.equal((await db.query('SELECT * FROM public.participants')).rows.length,0);
    assert.equal((await db.query('SELECT * FROM public.judge_registrations()')).rows.length,1);
    for(const sql of ['SELECT * FROM public.admin_accounts()',`SELECT public.admin_set_account('${judge}','admin',true,'Judge')`,`UPDATE public.scores SET coverage=0`,`UPDATE public.score_history SET user_id='${admin}'`,'DELETE FROM public.score_history']) await assert.rejects(db.query(sql),/Access denied|permission denied/);
    assert.equal((await db.query("UPDATE public.event_registrations SET payment_status='Paid' RETURNING id")).rows.length,0);
    await db.query('SELECT public.submit_lions_choice($1)',[registration]);
    assert.equal((await db.query('SELECT * FROM public.judge_score($1)',[registration])).rows.length,0);
    const submit=(values:unknown,section='body_paint',request=randomUUID())=>db.query('SELECT public.submit_section($1,$2,$3,$4) AS id',[registration,section,values,request]);
    for(const values of [{coverage:1.5},{coverage:'1e1'},{coverage:-1},{coverage:16},{coverage:true},{user_id:admin},{total_score:0}]) await assert.rejects(submit({...SECTIONS.body_paint,...values}),/Invalid|maximum|Unknown/);
    const request=randomUUID();const first=(await submit({coverage:'0',quality:0,engine_bay:0,original:0},'body_paint',request)).rows[0].id;
    assert.equal((await submit({coverage:'0',quality:0,engine_bay:0,original:0},'body_paint',request)).rows[0].id,first);
    await assert.rejects(submit({coverage:1,quality:0,engine_bay:0,original:0},'body_paint',request),/already used/);
    await submit({coverage:0,quality:0,engine_bay:0,original:0});
    let score=(await db.query('SELECT * FROM public.judge_score($1)',[registration])).rows[0];
    assert.equal(score.coverage,0);assert.equal(score.quality,0);assert.equal(score.total_score,null);assert.equal(String(score.progress_percentage),'23.53');
    assert.equal((await db.query('SELECT * FROM public.judge_history($1)',[registration])).rows.length,2);
    await submit('{"coverage":1.0,"quality":0,"engine_bay":0,"original":0}');
    assert.equal((await db.query('SELECT * FROM public.judge_score($1)',[registration])).rows[0].coverage,1);
    await submit({coverage:'000000000000000000000001',quality:0,engine_bay:0,original:0});
    assert.equal((await db.query('SELECT * FROM public.judge_score($1)',[registration])).rows[0].coverage,1);
    for(const [section,values] of Object.entries(SECTIONS)) await submit(values,section);
    score=(await db.query('SELECT * FROM public.judge_score($1)',[registration])).rows[0];assert.equal(score.total_score,180);
    await assert.rejects(db.query('SELECT public.admin_quick_edit($1,$2,$3,$4)',[registration,{},MAXIMA,randomUUID()]),/Access denied/);
    await as(admin);
    await db.query('SELECT public.admin_quick_edit($1,$2,$3,$4)',[registration,{},MAXIMA,randomUUID()]);
    score=(await db.query('SELECT * FROM public.scores')).rows[0];assert.equal(score.total_score,null);assert.equal(Number(score.progress_percentage),0);
    assert.equal((await db.query('SELECT status,lions_choice_votes FROM public.event_registrations')).rows[0].status,'Judged');
    const history=(await db.query("SELECT * FROM public.score_history WHERE action_type='admin_quick_edit'")).rows[0];assert.equal(history.section,null);assert.equal(history.user_id,admin);assert.equal(history.judge_name_snapshot,'Admin');
    await assert.rejects(db.query('SELECT public.admin_quick_edit($1,$2,$3,$4)',[registration,{},MAXIMA,randomUUID()]),/reload/);
    await db.query('SELECT public.admin_set_account($1,$2,$3,$4)',[judge,'judge',false,'Judge']);
    await as(judge);await assert.rejects(submit({coverage:0}),/Access denied/);
    await as(admin);await assert.rejects(db.query('SELECT public.admin_set_account($1,$2,$3,$4)',[admin,'judge',true,'Admin']),/at least one/);
    await db.exec('RESET ROLE');
    const attributed=(await db.query('SELECT * FROM public.score_history WHERE id=$1',[first])).rows[0];assert.equal(attributed.user_id,judge);
    await db.query('DELETE FROM auth.users WHERE id=$1',[judge]);
    const retained=(await db.query('SELECT * FROM public.score_history WHERE id=$1',[first])).rows[0];assert.equal(retained.user_id,null);assert.equal(retained.judge_name_snapshot,'Judge');
    assert.equal(Object.keys(retained.score_values_after as object).length,FIELDS.length);
  }finally{await close();}
});
test('provisioning uses confirmed Admin createUser only, returns no password and compensates failed roles',async()=>{
  const calls:unknown[]=[];const id=randomUUID();
  const api={createUser:async(value:unknown)=>{calls.push(value);return {data:{user:{id}},error:null};},deleteUser:async(value:unknown)=>{calls.push({delete:value});return {error:null};}} as unknown as SupabaseClient['auth']['admin'];
  const input={email:'new@example.invalid',password:'Test-only-password!',name:'New Judge',role:'judge' as const};
  assert.deepEqual(await provisionAccount(api,input,async()=>{}),{id});assert.deepEqual(calls,[{email:input.email,password:input.password,email_confirm:true}]);
  await assert.rejects(provisionAccount(api,input,async()=>{throw new Error(input.password);}),/role assignment failed/);
  assert.deepEqual(calls.at(-1),{delete:id});
  const adminModule=await readFile('src/supabase/admin.ts','utf8');assert.match(adminModule,/import 'server-only'/);
  const forms=await readFile('app/admin/users/forms.tsx','utf8');assert.doesNotMatch(forms,/SUPABASE_SECRET|SERVICE_ROLE/);
});
