import { PageHeader, StatusBadge } from '../../components/ui';
import Link from 'next/link';
import { requireStaff } from '../../../src/auth/session';
import { eventContext,registrations,rpc } from '../../../src/workflows/data';
import { STATUSES } from '../../../src/workflows/types';
import { StaffShell } from '../../components/staff-shell';
import { EventPicker,Historical,Progress } from '../../components/workflow';
export default async function Registrations({searchParams}:{searchParams:Promise<{q?:string;status?:string;paid?:string}>}){const {client,profile}=await requireStaff(true);const {events,event}=await eventContext(client);const p=await searchParams;const [rows,inbox]=await Promise.all([event?registrations(client,event.id):Promise.resolve([]),rpc<{requests:unknown[]}>(client,'admin_registration_requests')]);const pendingCount=inbox.requests.length;const q=(p.q??'').toLocaleLowerCase();const shown=rows.filter(r=>(!p.status||(p.status==='attending'?['Checked-in','Judged'].includes(r.status??''):p.status==='active'?['Registered','Checked-in','Judged'].includes(r.status??''):r.status===p.status))&&(!p.paid||r.payment_status===p.paid)&&`${r.car_number} ${r.vehicle_year} ${r.vehicle_make} ${r.vehicle_model} ${r.participant.name}`.toLocaleLowerCase().includes(q));
 const table=<div className="table-wrap"><table><thead><tr><th>Car #</th><th>Vehicle</th><th>Participant</th><th>Status</th><th>Payment</th><th>Judging</th><th>Actions</th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td data-label="Car #"><Link href={`/admin/registrations/${r.id}`}>{r.car_number?`#${r.car_number}`:'TBD'}</Link></td><td data-label="Vehicle">{r.vehicle_year} {r.vehicle_make} {r.vehicle_model}</td><td data-label="Participant"><Link href={`/admin/participants/${r.participant_id}`}>{r.participant.name}</Link></td><td data-label="Status"><StatusBadge value={r.status}/></td><td data-label="Payment"><StatusBadge value={r.payment_status}/></td><td data-label="Judging"><Progress value={Number(r.score?.progress_percentage??0)}/><small>Score: {r.score?.total_score??'Incomplete'}</small></td><td data-label="Actions"><div className="registration-row-actions"><Link className="button secondary" href={`/admin/registrations/${r.id}`}>View</Link> {r.status==='Registered'&&!event?.legacy_source_key&&<Link className="button secondary" href={`/admin/check-in/${r.participant_id}#car-${r.car_id}`}>Check In</Link>} {r.car_number&&<Link className="button secondary" href={`/judge/registrations/${r.id}?entry=judge`}>Judge</Link>}</div></td></tr>)}</tbody></table>{!shown.length&&<p className="empty">No registrations match. Choose a participant to register an existing or new car.</p>}</div>;
 return <StaffShell role={profile.app_role} name={profile.display_name}><PageHeader title={`Registrations / Cars`} actions={<Link className="button secondary registration-requests-link" href="/admin/registration-requests">Registration Requests{pendingCount>0&&<span className="request-count" aria-label={`${pendingCount} pending requests`}>{pendingCount}</span>}</Link>}/><EventPicker events={events} event={event}/>{event&&<Historical event={event}/>}<div className="actions"><Link className="button" href="/admin/participants">Find participant / walk-in</Link><Link className="button secondary" href="/admin/import">Import CSV</Link></div><form className="filters"><label>Search participant, car or number<input name="q" defaultValue={p.q}/></label><label>Status<select name="status" defaultValue={p.status??''}><option value="">All statuses</option><option value="active">All except Archived</option><option value="attending">Attending (Checked-in / Judged)</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Payment<select name="paid" defaultValue={p.paid??''}><option value="">All payments</option><option>Paid</option><option>Unpaid</option></select></label><button>Filter</button><Link href="/admin/registrations">Clear</Link></form><p>{shown.length} of {rows.length} registrations</p>{table}</StaffShell>;
}
