'use client';
import {useRouter} from 'next/navigation';
import {useState} from 'react';
import Link from 'next/link';
import {StatusBadge} from '../../components/ui';
import {Progress} from '../../components/workflow';
import {STATUSES,type Registration} from '../../../src/workflows/types';
type Row=Pick<Registration,'id'|'car_id'|'participant_id'|'car_number'|'vehicle_year'|'vehicle_make'|'vehicle_model'|'vehicle_color'|'status'|'payment_status'|'score'>&{participant:{name:string}};
export function RegistrationTable({rows,historical,initial,localPreview=false,leftIds=[]}:{rows:Row[];historical:boolean;localPreview?:boolean;leftIds?:string[];initial:{q?:string;status?:string;paid?:string}}){
const router=useRouter(); const [left,setLeft]=useState(leftIds);
function toggleLeft(id:string){const next=left.includes(id)?left.filter(v=>v!==id):[...left,id];document.cookie='local-left-show='+encodeURIComponent(JSON.stringify(next))+'; Path=/; SameSite=Strict; Max-Age=604800';setLeft(next);router.refresh();}
const [q,setQ]=useState(initial.q??''),[status,setStatus]=useState(initial.status??''),[paid,setPaid]=useState(initial.paid??'');
const shown=rows.filter(r=>(!status||(status==='unjudged'?r.status==='Checked-in'&&Number(r.score?.progress_percentage??0)<100&&!left.includes(r.id):status==='left'?left.includes(r.id):status==='attending'?['Checked-in','Judged'].includes(r.status??''):status==='active'?['Registered','Checked-in','Judged'].includes(r.status??''):r.status===status))&&(!paid||r.payment_status===paid)&&[r.car_number,r.car_number?'#'+r.car_number:'TBD',r.vehicle_year,r.vehicle_make,r.vehicle_model,r.vehicle_color,r.participant.name].join(' ').toLocaleLowerCase().includes(q.trim().toLocaleLowerCase()));
 const table=<div className="table-wrap"><table><thead><tr><th>Car #</th><th>Vehicle</th><th>Participant</th><th>Status</th><th>Payment</th><th>Judging</th><th>Actions</th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td data-label="Car #"><Link href={`/admin/registrations/${r.id}`}>{r.car_number?`#${r.car_number}`:'TBD'}</Link></td><td data-label="Vehicle">{r.vehicle_year} {r.vehicle_make} {r.vehicle_model}</td><td data-label="Participant"><Link href={`/admin/participants/${r.participant_id}`}>{r.participant.name}</Link></td><td data-label="Status"><StatusBadge value={r.status}/>{left.includes(r.id)&&<small>Left Show (local)</small>}</td><td data-label="Payment"><StatusBadge value={r.payment_status}/></td><td data-label="Judging"><Progress value={Number(r.score?.progress_percentage??0)}/><small>Score: {r.score?.total_score??'Incomplete'}</small></td><td data-label="Actions"><div className="registration-row-actions"><Link className="button secondary" href={`/admin/registrations/${r.id}`}>View</Link> {r.status==='Registered'&&!historical&&<Link className="button secondary" href={`/admin/check-in/${r.participant_id}#car-${r.car_id}`}>Check In</Link>} {r.car_number&&!left.includes(r.id)&&<Link className="button secondary" href={`/judge/registrations/${r.id}?entry=judge`}>Judge</Link>}{localPreview&&!historical&&r.car_number&&<button type="button" className="secondary" onClick={()=>toggleLeft(r.id)}>{left.includes(r.id)?'Undo Left Show':'Mark Left Show'}</button>}</div></td></tr>)}</tbody></table>{!shown.length&&<p className="empty">No registrations match. Choose a participant to register an existing or new car.</p>}</div>;
 return <>{localPreview&&<p>Local preview: Left Show excludes cars from judging and awards in this browser only. Live records are unchanged.</p>}<form className="filters" onSubmit={e=>e.preventDefault()}><label>Search participant, car or number<input name="q" value={q} onChange={e=>setQ(e.target.value)}/></label><label>Status<select name="status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="unjudged">Unjudged attending cars</option>{localPreview&&<option value="left">Left Show (local)</option>}<option value="active">All except Archived</option><option value="attending">Attending (Checked-in / Judged)</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Payment<select name="paid" value={paid} onChange={e=>setPaid(e.target.value)}><option value="">All payments</option><option>Paid</option><option>Unpaid</option></select></label><button type="button" className="secondary" onClick={()=>{setQ('');setStatus('');setPaid('');}}>Clear</button></form><p role="status">Showing {shown.length} of {rows.length} cars</p>{table}</>;
}
