'use client';
import { useActionState, useEffect, useRef, useState } from 'react';
import { X } from 'lucide-react';
import { createAccount, updateAccount, updateCredentials } from './actions';
export type Account={id:string;email:string;display_name:string;app_role:'admin'|'judge';is_active:boolean};
type Selection={mode:'create'|'edit'|'reset';account?:Account};
export function AccountsTable({accounts}:{accounts:Account[]}) {
 const [selection,setSelection]=useState<Selection|null>(null);
 return <><div className="users-toolbar"><button onClick={()=>setSelection({mode:'create'})}>Create New Account</button></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Actions</th></tr></thead><tbody>{accounts.map(account=><tr key={account.id}><td data-label="Name">{account.display_name}{!account.is_active&&<small className="hint"> · Inactive</small>}</td><td data-label="Email">{account.email}</td><td data-label="Role">{account.app_role==='admin'?'Admin':'Judge'}</td><td data-label="Actions"><div className="users-actions"><button className="secondary" onClick={()=>setSelection({mode:'edit',account})}>Edit</button><button className="secondary" onClick={()=>setSelection({mode:'reset',account})}>Reset Password</button></div></td></tr>)}</tbody></table></div>{selection&&<AccountDialog selection={selection} close={()=>setSelection(null)}/>}</>;
}
function AccountDialog({selection,close}:{selection:Selection;close:()=>void}) {
 const dialog=useRef<HTMLDialogElement>(null);
 const {mode,account}=selection;
 const [state,action,pending]=useActionState(mode==='create'?createAccount:mode==='edit'?updateAccount:updateCredentials,{message:''});
 useEffect(()=>{dialog.current?.showModal();},[]);
 const title=mode==='create'?'Create New Account':mode==='edit'?'Edit Account':'Reset Password';
 return <dialog ref={dialog} className="account-dialog" aria-labelledby="account-dialog-title" onCancel={e=>{if(pending)e.preventDefault();}} onClose={close}><header className="account-dialog-header"><h2 id="account-dialog-title">{title}</h2><button type="button" className="secondary" aria-label="Close dialog" disabled={pending} onClick={()=>dialog.current?.close()}><X size={20}/></button></header>{account&&<p>{account.display_name} · {account.email}</p>}{state.success?<><p role="status">{state.message}</p><button onClick={()=>dialog.current?.close()}>Done</button></>:<form action={action} className="stack">{account&&<input type="hidden" name="id" value={account.id}/>} {mode!=='reset'?<><label>Name<input name="name" defaultValue={account?.display_name} minLength={2} maxLength={80} required autoComplete="off"/></label><label>Email<input name="email" type="email" defaultValue={account?.email} maxLength={254} required autoComplete="off"/></label></>:<input type="hidden" name="email" value={account?.email}/>} {mode!=='edit'&&<><label>{mode==='create'?'Initial password':'New password'}<input name="password" type="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label><p className="hint">At least 12 characters (maximum 72 bytes). Share it directly with the user. No email is sent.</p></>}{mode!=='reset'&&<label>Role<select name="role" defaultValue={account?.app_role??'judge'}><option value="judge">Judge</option><option value="admin">Admin</option></select></label>}{mode==='edit'&&<label className="checkbox"><input type="checkbox" name="active" defaultChecked={account?.is_active}/>Active access</label>}<p className="message" role="status">{state.message}</p><div className="users-actions"><button disabled={pending}>{pending?'Saving…':mode==='create'?'Create account':mode==='edit'?'Save changes':'Set new password'}</button><button type="button" className="secondary" disabled={pending} onClick={()=>dialog.current?.close()}>Cancel</button></div></form>}</dialog>;
}
