'use client';
import { useRef, useState } from 'react';
import { LocationInput } from '../components/location-input';
import { PhoneInput } from '../components/phone-input';
import { formatPhone } from '../../src/workflows/phone';
import Link from "next/link";

import { findReturning, submitRegistration, chooseReturning } from './actions';
type Match={token:string;participant:{name:string;city:string|null;state:string|null};cars:Car[]};
type Car={registered:boolean;id:string;year:number;make:string;model:string};
export function RegistrationForm({eventId}:{eventId:string}){
 const lookupKey=useRef('');
 const [candidates,setCandidates]=useState<(Omit<Match,'cars'>&{vehicles:{year:number;make:string;model:string}[]})[]>([]);
 async function choose(token:string){setBusy(true);try{const result=await chooseReturning(token);if(result.matched){setName(result.participant.name);setParticipant(result.participant);setToken(result.token);setCars(result.cars);setNewCars([]);setManual(false);setCandidates([]);}else setMessage(result.error);}catch{setMessage('Unable to load this match. Please try again.');}finally{setBusy(false);}}
 const [suggestion,setSuggestion]=useState<Match|null>(null),[confirmNew,setConfirmNew]=useState(false);
 const [participant,setParticipant]=useState<{name:string;city:string|null;state:string|null}|null>(null);
 const [attended,setAttended]=useState(''),[contact,setContact]=useState(''),[name,setName]=useState(''),[token,setToken]=useState<string|null>(null),[cars,setCars]=useState<Car[]>([]),[selected,setSelected]=useState<string[]>([]),[manual,setManual]=useState(false),[newCars,setNewCars]=useState([{year:'',make:'',model:'',color:''}]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[done,setDone]=useState(false),[pending,setPending]=useState(false),[request]=useState(()=>crypto.randomUUID());
 async function lookup(){setBusy(true);setMessage('');setCandidates([]);try{const result=await findReturning(name,contact);if(result.matched){setName(result.participant.name);setParticipant(result.participant);setToken(result.token);setCars(result.cars);setNewCars([]);setManual(false);}else if(result.candidates){setCandidates(result.candidates);setManual(false);}else if(result.pending){setMessage('Your registration request has already been received and is awaiting staff review. Please visit the check-in table when you arrive.');setManual(false);}else{setMessage(result.error??'We could not find a unique match. Enter your details below and staff will help match your record at check-in.');setManual(true);}}catch{setMessage('Unable to look up your record. Please try again.');}finally{setBusy(false);}}
 if(done)return <div className="card" role="status"><h2>{pending?'Your request has been received':'You’re pre-registered!'}</h2><p>{pending?'Staff will review your details and match any existing participant or car records. ':''}Please visit the check-in table when you arrive to confirm your details, arrange payment and receive your car number and sheet.</p><div className="public-registration-buttons"><button type="button" onClick={()=>window.location.assign('/register')}>Next Registration</button><Link className="button secondary" href="/">Back to home</Link></div></div>;
 return <form className="stack" noValidate onBlurCapture={async e=>{if(token||confirmNew||!['email','phone'].includes(e.target.getAttribute('name')??''))return;const values=new FormData(e.currentTarget);const email=String(values.get('email')??'').trim(),phone=String(values.get('phone')??'').trim();const key=JSON.stringify([name,email,phone]);if(!name||(!email&&!phone)||lookupKey.current===key)return;lookupKey.current=key;try{for(const contactValue of [email,phone]){if(!contactValue)continue;const match=await findReturning(name,contactValue);if(lookupKey.current!==key)return;if(match.matched){setSuggestion(match);setMessage('We found a possible existing record. Is this you?');return;}}}catch{/* Submit retries lookup and reports network errors. */}}} onSubmit={async e=>{e.preventDefault();const invalid=e.currentTarget.querySelector<HTMLInputElement|HTMLSelectElement>('input:invalid,select:invalid');if(invalid){const label=invalid.closest('label')?.textContent?.trim()||'A required field';setMessage(invalid.type==='number'&&invalid.min==='1900'?'Car year must be a whole number from 1900 to 2155.':`${label}: ${invalid.validationMessage}`);invalid.focus();invalid.scrollIntoView({block:'center',behavior:'smooth'});return;}const form=new FormData(e.currentTarget);setBusy(true);setMessage('');try{const result=await submitRegistration({event:eventId,request,token,confirmNew,selected,cars:newCars,details:{name,email:String(form.get('email')??''),phone:String(form.get('phone')??''),city:String(form.get('city')??''),state:String(form.get('state')??'')}});if(result.suggestion){setSuggestion(result.suggestion);setMessage('We found a possible existing record. Choose below before continuing.');}else if(result.ok){setPending(result.pending);setDone(true);}else setMessage(result.error||'Registration was not saved. Please try again.');}catch{setMessage('Unable to submit. Please try again.');}finally{setBusy(false);}}}>
 {message&&<p role="alert" className="message">{message}</p>}<fieldset disabled={busy}><label>Have you attended before?<select value={attended} onChange={e=>{setAttended(e.target.value);setToken(null);setCars([]);setSelected([]);setNewCars([{year:'',make:'',model:'',color:''}]);setManual(e.target.value==='No');setMessage('');}} required><option value="">Choose an answer</option>{['Yes','No','Unsure'].map(x=><option key={x}>{x}</option>)}</select></label>
 {attended&&attended!=='No'&&!manual&&!token&&<label>Full name or last name<input value={name} onChange={e=>{setName(e.target.value);setToken(null);setSelected([]);}} required minLength={2} maxLength={255} autoComplete="name"/></label>}
 {attended!=='No'&&attended&&!token&&<div className="card"><label>Phone number or email used previously<input value={contact} onChange={e=>setContact(e.target.value)} onBlur={e=>setContact(formatPhone(e.target.value))} maxLength={255}/></label><div className="public-registration-buttons"><button type="button" onClick={lookup} disabled={busy||(!name.trim()&&!contact.trim())}>Find my cars</button><button className="secondary" type="button" onClick={()=>setManual(true)}>I don’t remember / enter my details</button></div><p>Search with a full name, last name, phone number, or email. Add a second detail to narrow the results.</p></div>}
 {candidates.length>0&&<section className="card"><h2>Is one of these you?</h2>{candidates.map(candidate=><div className="registration-candidate" key={candidate.token}><strong>{candidate.participant.name}</strong><p>{[candidate.participant.city,candidate.participant.state].filter(Boolean).join(', ')}</p>{candidate.vehicles?.length>0&&<ul className="candidate-vehicles">{candidate.vehicles.map((vehicle,index)=><li key={index}>{vehicle.year} {vehicle.make} {vehicle.model}</li>)}</ul>}<button type="button" disabled={busy} onClick={()=>choose(candidate.token)}>This is me</button></div>)}<button type="button" className="secondary candidate-none" onClick={()=>{setCandidates([]);setManual(true);}}>None of these — enter my details</button></section>}
 {token&&<div className="card"><h2>Is this you?</h2><strong>{participant?.name}</strong><p>{[participant?.city,participant?.state].filter(Boolean).join(', ')||'Location not recorded'}</p><div className="public-registration-buttons"><button type="button" className="secondary" onClick={()=>{setToken(null);setParticipant(null);setCars([]);setSelected([]);setNewCars([{year:'',make:'',model:'',color:''}]);setManual(false);setMessage('Check your name and contact information, then try again.');}}>Not me, try again</button><button type="button" className="secondary" onClick={()=>{setToken(null);setParticipant(null);setCars([]);setSelected([]);setName('');setContact('');setAttended('No');setManual(true);setNewCars([{year:'',make:'',model:'',color:''}]);setMessage('Enter your details below. Your participant record and cars will be created when you register.');}}>Create New Participant</button></div><h2>Your cars</h2>{cars.some(car=>car.registered)&&<p>You already have a car registered for this event. You can select another car or add a new one below.</p>}{cars.map(car=><label className="checkbox" key={car.id}><input type="checkbox" disabled={car.registered} checked={car.registered||selected.includes(car.id)} onChange={e=>setSelected(e.target.checked?[...selected,car.id]:selected.filter(id=>id!==car.id))}/>{car.year} {car.make} {car.model}{car.registered&&<strong className="registration-existing-status">Already registered</strong>}</label>)}{!cars.length&&<p>No cars are on this record. Add a car below.</p>}<p>Choose one or more cars. Cars already registered for this event will not be registered twice.</p></div>}
 {(manual||token)&&<>{!token&&<div className="card stack"><h2>Your details</h2><label>Full name<input name="name" value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={255} autoComplete="name"/></label><label>Email (optional)<input name="email" type="email" maxLength={255} autoComplete="email"/></label><label>Phone (optional)<PhoneInput/></label><label>City<LocationInput kind="city" required/></label><label>State<LocationInput kind="state" required/></label></div>}
 {suggestion&&<section className="card"><h2>Is this you?</h2><strong>{suggestion.participant.name}</strong><p>{[suggestion.participant.city,suggestion.participant.state].filter(Boolean).join(', ')}</p><ul>{suggestion.cars.map(car=><li key={car.id}>{car.year} {car.make} {car.model}{car.registered?' · Already registered':''}</li>)}</ul><div className="public-registration-buttons"><button type="button" onClick={()=>{setParticipant(suggestion.participant);setToken(suggestion.token);setCars(suggestion.cars);setManual(false);setSuggestion(null);setMessage('Select your existing car, or keep the new car details below.');}}>Yes, use my existing record</button><button className="secondary" type="button" onClick={()=>{setConfirmNew(true);setSuggestion(null);setMessage('Continue with your entered details, then click Register. Shared email addresses are allowed.');}}>Not me, continue as new</button></div></section>}{newCars.map((car,i)=><div className="card stack" key={i}><h2>Car Details</h2>{(['year','make','model','color'] as const).map(field=><label key={field}>{field==='year'?'Year':field==='make'?'Make':field==='color'?'Car color (optional)':'Model'}<input aria-label={`Car ${i+1} ${field}`} value={car[field]} type={field==='year'?'number':'text'} min={field==='year'?1900:undefined} max={field==='year'?2155:undefined} maxLength={field==='color'?80:255} required={field!=='color'} onChange={e=>setNewCars(newCars.map((c,j)=>i===j?{...c,[field]:e.target.value}:c))}/>{field==='year'&&car.year&&(Number(car.year)<1900||Number(car.year)>2155||!Number.isInteger(Number(car.year)))&&<span role="alert">Car year must be 1900 or newer (up to 2155).</span>}</label>)}<button type="button" className="secondary" onClick={()=>setNewCars(newCars.filter((_,j)=>j!==i))}>Remove car</button></div>)}
 {newCars.length<10&&<button type="button" className="secondary" onClick={()=>setNewCars([...newCars,{year:'',make:'',model:'',color:''}])}>Add another car</button>}
 <p>{token?'New cars will be added to your participant record and pre-registered now. Visit the check-in table to receive your car number.':'Your participant information and cars will be saved and pre-registered when you submit.'}</p><button disabled={busy||(!selected.length&&!newCars.length)}>{busy?'Submitting…':'Register'}</button></>}
 </fieldset><p role="status">{message}</p></form>;
}
