import { ArrowLeft } from 'lucide-react';
import { LionsLogo } from '../../../../components/lions-logo';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import { headers } from 'next/headers';
import QRCode from 'qrcode';
import { requireStaff } from '../../../../../src/auth/session';
import { registrationDetail } from '../../../../../src/workflows/data';
import { PrintButton } from '../../../../components/print-button';
export default async function CarSheet({params}:{params:Promise<{id:string}>}){const {id}=await params;const {client}=await requireStaff(true);const {event,registration:r}=await registrationDetail(client,id);if(!r.car_number)redirect(`/admin/check-in/${r.participant_id}`);const h=await headers();const host=h.get('host')??'127.0.0.1:3000';const base=process.env.NEXT_PUBLIC_APP_URL??`${/^(localhost|127\.0\.0\.1)(:\d+)?$/.test(host)?'http':'https'}://${host}`;const url=new URL(`/judge/registrations/${id}`,base).href;const svg=await QRCode.toString(url,{type:'svg',errorCorrectionLevel:'M',margin:4,width:210});return <main className="print-wrapper"><div className="actions print-toolbar no-print"><Link href={`/admin/registrations/${id}`}><ArrowLeft className="action-icon" size={18} strokeWidth={1.75} aria-hidden="true"/> Registration</Link><PrintButton/><Link className="button secondary" href={`/admin/check-in/${r.participant_id}`}>Done / check in another car</Link><Link className="button secondary" href="/admin/participants">Next participant</Link></div><article className="car-sheet"><header className="sheet-brand"><LionsLogo/><div><p>Zionsville Lions Club</p><h1>{event.event_year} {event.name}</h1>{event.legacy_source_key&&<p className="sheet-event-year">Historical legacy snapshot</p>}</div></header><div className="sheet-number">Car {r.car_number?`#${r.car_number}`:'Pre-registered'}</div><h2>{r.vehicle_year} {r.vehicle_make} {r.vehicle_model}</h2><p className="sheet-class">Classification:<strong>{r.classification??'Unclassified'}</strong></p><hr/><div className="sheet-participant"><p>Participant:<strong>{r.participant.name}</strong></p><p className="sheet-location">{[r.participant.city,r.participant.state].filter(Boolean).join(', ')}</p></div><hr/><div className="sheet-qr"><div role="img" aria-label={`QR code for judging car ${r.car_number}`} dangerouslySetInnerHTML={{__html:svg}}/><div><h3>Scan for judging progress</h3><p>Judges sign in to enter scores.</p><p>{r.car_number?`#${r.car_number}`:'Pre-registered'} · {event.event_year}</p></div></div><p className="qr-address">{url}</p></article><p className="no-print hint">Use your browser’s print dialog → Save as PDF. For phones, the QR URL must use a reachable host; set NEXT_PUBLIC_APP_URL to the approved deployed or LAN address before printing event-day sheets.</p></main>;}
