'use client';
import { ReportFooter } from '../../../components/report-footer';
import { DashboardInsights } from '../../../components/dashboard-insights';
import { useEffect, useState } from 'react';
import type { Registration,EventRow } from '../../../../src/workflows/types';
import { dashboardInsights } from '../../../../src/workflows/dashboard';
import { LionsLogo } from '../../../components/lions-logo';
import { PrintButton } from '../../../components/print-button';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
export function FullScoreReport({event,rows,judges,generated,filename,dashboard,attendance}:{dashboard:ReturnType<typeof dashboardInsights>;attendance:{year:number;previousYear:number|null;previousCount:number|null};event:EventRow;rows:Registration[];judges:{name:string;sections:string[]}[];generated:string;filename:string}){
 useEffect(()=>{const previous=document.title;document.title=filename;return()=>{document.title=previous;};},[filename]);
 const [weather,setWeather]=useState('');const judgedRows=rows.filter(r=>r.status==='Judged').sort((a,b)=>a.car_number===null?(b.car_number===null?0:1):b.car_number===null?-1:BigInt(a.car_number)<BigInt(b.car_number)?-1:BigInt(a.car_number)>BigInt(b.car_number)?1:0);const attended=rows.filter(r=>r.status==='Checked-in'||r.status==='Judged');const insights=dashboardInsights(attended,[],false);

 // Organizer-confirmed recap figures for this event only; never alter stored scores.
 const recapJudging=event.id==='143b6773-ca94-4a44-9ec6-006ba5ca36ea'?{count:83,total:87,left:4}:undefined;
 const noShows=rows.filter(r=>r.status==='Registered');
 const unpaidAttendees=attended.filter(r=>r.payment_status==='Unpaid');
 function followUp(title:string,list:Registration[],noShow=false){return <section className="report-followup"><div className="recap-box"><h2>{title}</h2><p>{list.length} cars · Staff follow-up</p>{list.length?<table className={noShow?'no-show-followup-table':undefined}><thead><tr>{[...(noShow?[]:['Car #']),'Participant','Vehicle','Paid?',...(noShow?['Phone','Email','City, State']:['Contact','Address'])].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{list.map(r=><tr key={r.id}>{!noShow&&<td>{r.car_number??'Unassigned'}</td>}<td>{r.participant.name}</td><td>{r.vehicle_year} {r.vehicle_make} {r.vehicle_model}</td><td>{r.payment_status}</td>{noShow?<><td>{r.participant.phone||'—'}</td><td>{r.participant.email||'—'}</td><td>{[r.participant.city,r.participant.state].filter(Boolean).join(', ')||'—'}</td></>:<><td>{r.participant.email||'Email not recorded'}<br/>{r.participant.phone||'Phone not recorded'}</td><td>{r.participant.address}<br/>{[r.participant.city,r.participant.state,r.participant.zip].filter(Boolean).join(', ')}</td></>}</tr>)}</tbody></table>:<p>None.</p>}</div><ReportFooter generated={generated}/></section>;}
 function ranking(title:string,items:typeof insights.makes){return <section className="recap-box"><h2>{title}</h2><table><thead><tr><th>{title.includes('makes')?'Make':title.includes('class')?'Class':'City, State'}</th><th>Cars</th><th>% attended</th></tr></thead><tbody>{items.map(r=><tr key={r.label}><td>{r.label}</td><td>{r.count}</td><td>{r.percent.toFixed(1)}%</td></tr>)}</tbody></table>{!items.length&&<p>No attendance recorded.</p>}</section>;}
 const runningTitle=JSON.stringify(`${event.event_year} · ${event.name}`).replace(/</g,'\\3c ');
 const footerText=JSON.stringify(`Report generated ${generated} Eastern`).replace(/</g,'\\3c ');
 return <main className="full-score-report"><style>{`@media print { @page fullscores { @bottom-left { content: ${runningTitle} "\\A" ${footerText}; white-space: pre-line; line-height: 1.5; font: 8pt "Helvetica Neue", Arial, sans-serif; color: #656868; vertical-align: middle; } @bottom-right { content: "Built by    BRAM"; font: 9pt "Bram Footer Mark", Arial, sans-serif; color: #656868; vertical-align: middle; } @top-center { content: none; } } @page fullscores:first { @top-center { content: none; border: 0; padding: 0; } } }`}</style><span className="recap-font-preload" aria-hidden="true"></span><div className="actions announcer-toolbar no-print"><Link className="button secondary" href="/admin/scores"><ArrowLeft size={18} aria-hidden="true"/>Scores</Link><PrintButton title={filename}/></div><label className="no-print report-weather-input">Optional event weather summary (your observation)<textarea maxLength={300} value={weather} onChange={e=>setWeather(e.target.value)} placeholder="For example: Mild and sunny, with a brief afternoon shower."/><small>Included in this printout only; not saved to the event.</small></label>
 <section className="report-cover"><header className="announcer-heading recap-heading"><LionsLogo/><div><p className="recap-club">ZIONSVILLE LIONS CLUB</p><h1>American Dream Car Show</h1><p className="recap-subtitle">{event.event_year} Event Recap</p></div></header><section className="recap-box recap-event-details"><h2>Event Details</h2><p><strong>Date:</strong> {event.event_date?new Intl.DateTimeFormat('en-US',{month:'long',day:'2-digit',year:'numeric',timeZone:'UTC'}).format(new Date(event.event_date.slice(0,10)+'T12:00:00Z')):''}</p><p><strong>Location:</strong> Lion&apos;s Park, Zionsville, IN</p><p><strong>Weather:</strong> {weather.trim()}</p></section><DashboardInsights data={dashboard} attendance={attendance} report reportPayments={{prepaidNoShows:noShows.filter(r=>r.payment_status==='Paid').length,unpaidAttendees:unpaidAttendees.length}} reportJudging={recapJudging} section="charts"/><ReportFooter generated={generated}/></section><section className="report-comparisons"><DashboardInsights data={dashboard} attendance={attendance} report section="comparisons"/><div className="report-rankings">{ranking('Top 7 makes',insights.makes)}{ranking('Top 7 locations',insights.locations)}{ranking('Cars by decade class',insights.decades)}</div><ReportFooter generated={generated}/></section>
 <section className="report-score-section"><div className="recap-box recap-score-box"><h2>Judged cars - score summary</h2><p className="report-note">Only the {judgedRows.length} registrations marked Judged in this event, sorted by car number. A dash means no score or incomplete total; zero is a valid score. Current scores are shown, not a history of revisions.</p><table className="full-score-table"><thead><tr>{[['Car #',''],['Participant',''],['Vehicle',''],['Paint','/60'],['Plating','/10'],['Interior','/40'],['Wheels & tires','/20'],['Engine','/40'],['Appearance','/10'],['Total','/180']].map(([h,max])=><th key={h}><span>{h}</span>{max&&<><br/>{max}</>}</th>)}</tr></thead><tbody>{judgedRows.map(r=><tr key={r.id}><td>{r.car_number??'Unassigned'}</td><td>{r.participant.name}</td><td>{r.vehicle_year} {r.vehicle_make} {r.vehicle_model}</td><td>{r.score?.overall_paint??'—'}</td><td>{r.score?.plating_brass??'—'}</td><td>{r.score?.overall_interior??'—'}</td><td>{r.score?.rims_hub_caps!=null&&r.score?.tires!=null?r.score.rims_hub_caps+r.score.tires:'—'}</td><td>{r.score?.overall_engine??'—'}</td><td>{r.score?.appearance??'—'}</td><td><strong>{r.score?.total_score??'—'}</strong></td></tr>)}</tbody></table>{!judgedRows.length&&<p>No cars are marked Judged in this event yet.</p>}</div><section className="recap-box recap-judges-box"><h2>Judges who submitted scores</h2>{judges.length?<ul className="report-judges">{judges.map(judge=><li key={judge.name}><strong>{judge.name}</strong> — {judge.sections.length?judge.sections.join(', '):'Section not recorded'}</li>)}</ul>:<p>No attributed section submissions recorded.</p>}</section><ReportFooter generated={generated}/></section>
 {followUp("Cars registered but did not attend",noShows,true)}{followUp("Checked-in cars with unpaid balances",unpaidAttendees)}
 </main>;
}
