'use client';
import { ReportFooter } from '../../../components/report-footer';
import { useState } from 'react';
import type { Registration,EventRow } from '../../../../src/workflows/types';
import { dashboardInsights } from '../../../../src/workflows/dashboard';
import { LionsLogo } from '../../../components/lions-logo';
import { PrintButton } from '../../../components/print-button';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
export function FullScoreReport({event,rows,judges,generated,filename}:{event:EventRow;rows:Registration[];judges:string[];generated:string;filename:string}){
 const [weather,setWeather]=useState('');const judgedRows=rows.filter(r=>r.status==='Judged').sort((a,b)=>a.car_number===null?(b.car_number===null?0:1):b.car_number===null?-1:BigInt(a.car_number)<BigInt(b.car_number)?-1:BigInt(a.car_number)>BigInt(b.car_number)?1:0);const attended=rows.filter(r=>r.status==='Checked-in'||r.status==='Judged');const insights=dashboardInsights(attended,[],false);
 function ranking(title:string,items:typeof insights.makes){return <section><h2>{title}</h2><table><thead><tr><th>{title.includes('makes')?'Make':'City, State'}</th><th>Cars</th><th>% attended</th></tr></thead><tbody>{items.map(r=><tr key={r.label}><td>{r.label}</td><td>{r.count}</td><td>{r.percent.toFixed(1)}%</td></tr>)}</tbody></table>{!items.length&&<p>No attendance recorded.</p>}</section>;}
 return <main className="full-score-report"><div className="actions announcer-toolbar no-print"><Link className="button secondary" href="/admin/scores"><ArrowLeft size={18} aria-hidden="true"/>Scores</Link><PrintButton title={filename}/></div><label className="no-print report-weather-input">Optional event weather summary (your observation)<textarea maxLength={300} value={weather} onChange={e=>setWeather(e.target.value)} placeholder="For example: Mild and sunny, with a brief afternoon shower."/><small>Included in this printout only; not saved to the event.</small></label>
 <section className="report-cover"><header className="announcer-heading"><LionsLogo/><div><h1>{event.name}</h1><p>{event.event_year} Full Score Report</p></div></header><p><strong>Date:</strong> {event.event_date??'Not recorded'} · <strong>Location:</strong> Lion&apos;s Park, Zionsville, IN</p><div className="report-counts"><div><strong>{attended.length}</strong><span>Cars attended</span></div><div><strong>{attended.filter(r=>r.status==='Judged').length}</strong><span>Cars judged</span></div></div><p className="report-note">Attendance means Checked-in or Judged status. Archived records do not establish attendance.{event.legacy_source_key?' This report uses the imported legacy snapshot.':''} Rankings count attended cars, including multiple cars from one participant. Vehicle details use event snapshots; locations use current participant details.</p><div className="report-rankings">{ranking('Top 5 makes',insights.makes)}{ranking('Top 5 locations',insights.locations)}</div><section><h2>Judges who submitted scores</h2>{judges.length?<ul className="report-judges">{judges.map(name=><li key={name}>{name}</li>)}</ul>:<p>No attributed section submissions recorded.</p>}</section>{weather.trim()&&<section><h2>Event weather</h2><p>{weather.trim()}</p><small>Organizer-provided observation.</small></section>}<ReportFooter generated={generated}/></section>
 <section className="report-score-section"><h2>Judged cars - score summary</h2><p>Only the {judgedRows.length} registrations marked Judged in this event, sorted by car number. A dash means no score or incomplete total; zero is a valid score. Current scores are shown, not a history of revisions.</p><table className="full-score-table"><thead><tr>{['Car #','Participant','Vehicle','Paint /60','Plating /10','Interior /40','Wheels & tires /20','Engine /40','Appearance /10','Total /180'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{judgedRows.map(r=><tr key={r.id}><td>{r.car_number??'Unassigned'}</td><td>{r.participant.name}</td><td>{r.vehicle_year} {r.vehicle_make} {r.vehicle_model}</td><td>{r.score?.overall_paint??'—'}</td><td>{r.score?.plating_brass??'—'}</td><td>{r.score?.overall_interior??'—'}</td><td>{r.score?.rims_hub_caps!=null&&r.score?.tires!=null?r.score.rims_hub_caps+r.score.tires:'—'}</td><td>{r.score?.overall_engine??'—'}</td><td>{r.score?.appearance??'—'}</td><td><strong>{r.score?.total_score??'—'}</strong></td></tr>)}</tbody></table>{!judgedRows.length&&<p>No cars are marked Judged in this event yet.</p>}<ReportFooter generated={generated}/></section>
 </main>;
}
