import { PageHeader } from '../../components/ui';
import { requireStaff } from '../../../src/auth/session';
import { eventContext,registrations,registrationDetail } from '../../../src/workflows/data';
import { label } from '../../../src/workflows/types';
import { FIELDS,MAXIMA } from '../../../src/domain/scoring';
import { CLASSES } from '../../../src/domain/awards';
import { StaffShell } from '../../components/staff-shell';
import { EventPicker,Historical } from '../../components/workflow';
import { ActionForm } from '../../components/action-form';
import { quickEdit } from '../../judge/actions';
import { ScoreTable } from './score-table';
export default async function Scores({searchParams}:{searchParams:Promise<{registration?:string;number?:string;sort?:string;order?:string;classification?:string}>}){const {client,profile}=await requireStaff(true);const context=await eventContext(client);const p=await searchParams;const direct=p.registration?await registrationDetail(client,p.registration):null;const event=direct?.event??context.event;const all=event?await registrations(client,event.id):[];const selected=direct?.registration??all.find(r=>r.car_number===p.number);const sort=['car_number','participant_name','appearance','overall_paint','overall_interior','overall_engine','total_score'].includes(p.sort??'')?p.sort!:'total_score';const direction=p.order==='asc'?1:-1;const rows=all.filter(r=>r.score&&(!p.classification||r.classification===p.classification));rows.sort((a,b)=>{if(sort==='car_number')return direction*(BigInt(a.car_number??0)<BigInt(b.car_number??0)?-1:BigInt(a.car_number??0)>BigInt(b.car_number??0)?1:0);if(sort==='participant_name')return direction*a.participant.name.localeCompare(b.participant.name);const x=a.score?.[sort],y=b.score?.[sort];return direction*(x==null?(y==null?0:-1):y==null?1:Number(x)-Number(y));});
 return <StaffShell role={profile.app_role} name={profile.display_name}><PageHeader title={`Scores`}/><EventPicker events={context.events} event={event}/>{event&&<Historical event={event}/>}<section className="card"><h2>Quick Edit by public car number</h2><form className="filters"><label>Car number<input name="number" inputMode="numeric" pattern="[0-9]+" defaultValue={selected?.car_number??p.number}/></label><button>Find registration</button></form>{p.number&&!selected&&<p>No registration with this number in the selected event.</p>}{selected&&<><h3>#{selected.car_number} · {selected.vehicle_year} {selected.vehicle_make} {selected.vehicle_model}</h3>{event?.judging_open&&!event.legacy_source_key?<ActionForm key={selected.id} action={quickEdit} submit="Save administrative Quick Edit"><input type="hidden" name="registration" value={selected.id}/><input type="hidden" name="request" value={crypto.randomUUID()}/><input type="hidden" name="expected" value={JSON.stringify(Object.fromEntries(FIELDS.map(k=>[k,selected.score?.[k]??null])))}/><p>Zero is valid. Blank fields remain incomplete. Saving recalculates progress and records an administrative history entry.</p><div className="score-fields">{FIELDS.map(field=><label key={field}>{label(field)} (0–{MAXIMA[field]})<input name={field} type="number" min={0} max={MAXIMA[field]} step={1} defaultValue={selected.score?.[field]??''}/></label>)}</div></ActionForm>:<p>Read-only scores. Historical events remain closed; new events must be open for judging to edit scores.</p>}</>}</section><form className="filters"><label>Classification<select name="classification" defaultValue={p.classification??''}><option value="">All classes</option>{CLASSES.map(c=><option key={c}>{c}</option>)}</select></label><label>Sort<select name="sort" defaultValue={sort}>{['car_number','participant_name','appearance','overall_paint','overall_interior','overall_engine','total_score'].map(s=><option value={s} key={s}>{label(s)}</option>)}</select></label><label>Order<select name="order" defaultValue={p.order??'desc'}><option value="desc">Descending</option><option value="asc">Ascending</option></select></label><button>Apply</button></form><ScoreTable rows={rows}/></StaffShell>;
}
