import { PageHeader } from '../../components/ui';
import Link from 'next/link';
import { requireStaff } from '../../../src/auth/session';
import { searchText } from '../../../src/workflows/types';
import { directory } from '../../../src/workflows/data';
import { StaffShell } from '../../components/staff-shell';
import { ActionForm } from '../../components/action-form';
import { saveParticipant } from '../workflow-actions';
import { ParticipantFields } from './fields';
export default async function Participants({searchParams}:{searchParams:Promise<{q?:string;sort?:string;order?:string}>}){const {client,profile}=await requireStaff(true);const [people,cars]=await directory(client);const params=await searchParams;const q=(params.q??'').slice(0,255),direction=params.order==='desc'?-1:1;const filtered=people.filter(p=>searchText(p.name).includes(searchText(q)));filtered.sort((a,b)=>direction*(params.sort==='name'?a.name.localeCompare(b.name):a.legacy_participant_id&&b.legacy_participant_id?Number(BigInt(a.legacy_participant_id)-BigInt(b.legacy_participant_id)):a.legacy_participant_id?-1:b.legacy_participant_id?1:a.id.localeCompare(b.id)));
 return <StaffShell role={profile.app_role} name={profile.display_name}><PageHeader title={`Participants`}/><p>Persistent directory · {people.length} participants · {cars.length} vehicles across all events.</p><details className="card"><summary>Add participant</summary><ActionForm action={saveParticipant} submit="Add participant"><ParticipantFields/></ActionForm></details><form className="filters"><label>Search by name<input name="q" defaultValue={q}/></label><label>Sort<select name="sort" defaultValue={params.sort??'id'}><option value="id">Legacy ID</option><option value="name">Name</option></select></label><label>Order<select name="order" defaultValue={params.order??'asc'}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><button>Search</button><Link href="/admin/participants">Clear</Link></form><p>{filtered.length} matching participants</p><div className="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Phone</th><th>City</th><th>Cars</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td data-label="ID">{p.legacy_participant_id??'New'}</td><td data-label="Name"><Link href={`/admin/participants/${p.id}`}>{p.name}</Link></td><td data-label="Phone">{p.phone}</td><td data-label="City">{p.city}</td><td data-label="Cars">{cars.filter(c=>c.participant_id===p.id).length}</td><td data-label="Actions"><Link href={`/admin/check-in/${p.id}`}>Check in</Link><Link href={`/admin/participants/${p.id}`}>View / pre-register cars</Link></td></tr>)}</tbody></table>{!filtered.length&&<p className="empty">No participants match this name.</p>}</div></StaffShell>;
}
